language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - "pip install -r requirements.txt"
    - "pip install nose"
    - "pip install nose-cov"
script:
    - nosetests --with-cov --cov-report term-missing --cov progressive tests/
after_success:
    coveralls --verbose
